Use Linux 5.10.43
Add the following buildroot config:
- BR2_LINUX_KERNEL_INSTALL_TARGET=y

Add the following linux config:
- CONFIG_BPF_LSM=y
- CONFIG_DEBUG_INFO_BTF=y
- CONFIG_IKHEADERS=y

Remove sysdig due to:
  ../sysdig-0.23.1/driver/ppm_fillers.c:611:15: error: implicit declaration of
  function ‘probe_kernel_read’; did you mean ‘kernel_read’?
  [-Werror=implicit-function-declaration]
    611 |  if (unlikely(probe_kernel_read(&tty, &sig->tty, sizeof(tty))))
        |               ^~~~~~~~~~~~~~~~~

Remove Falco due to:
  ../falco-module-0.24.0/driver/src/ppm_fillers.c:741:15: error: implicit
  declaration of function ‘probe_kernel_read’; did you mean ‘kernel_read’?
  [-Werror=implicit-function-declaration]
  741 |  if (unlikely(probe_kernel_read(&tty, &sig->tty, sizeof(tty))))
      |               ^~~~~~~~~~~~~~~~~

Remove hyperv-daemons due to:
  >>> hyperv-daemons 5.10.43 Downloading
  https://www.kernel.org/pub/linux/kernel/v4.x/linux-5.10.43.tar.xz
  HTTP request sent, awaiting response... 404 Not Found

Remove vbox-modules due to:

  CC [M]  /home/alban/go/src/k8s.io/minikube/out/buildroot/output/build/vbox-guest-5.2.42/vbox-modules//vboxsf/vfsmod.o
In file included from /home/alban/go/src/k8s.io/minikube/out/buildroot/output/build/vbox-guest-5.2.42/vbox-modules//vboxsf/vfsmod.h:21,
                 from /home/alban/go/src/k8s.io/minikube/out/buildroot/output/build/vbox-guest-5.2.42/vbox-modules//vboxsf/vfsmod.c:31:
/home/alban/go/src/k8s.io/minikube/out/buildroot/output/build/vbox-guest-5.2.42/vbox-modules//vboxsf/r0drv/linux/the-linux-kernel.h:132:11: fatal error: linux/smp_lock.h: No such file or directory
  132 | # include <linux/smp_lock.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.